fixed display of english data logger site
sensebox/sensebox-reboot pull request #202
Opened 2023-12-06 14:01 UTC by Thiemann96

Added english translation for the data logger

2023-12-06 14:19 UTC, buchwaldchassee approved these changes

2023-12-11 06:43 UTC, mariopesch commented
@Thiemann96 site empty and disappears from the navbar after clicking on EN

2023-12-11 12:56 UTC, mariopesch requested changes
add englisch translations

2023-12-11 13:23 UTC, buchwaldchassee approved these changes

2023-12-12 15:06 UTC, merged